[project]
name = "server"
version = "0.1.0"
description = ""
authors = [
    {name = "bdyldo",email = "dyl123455@outlook.com"}
]
readme = "../README.md"
requires-python = ">=3.12"
dependencies = [
    # Core web framework
    "fastapi (>=0.116.1,<0.117.0)",
    "python-socketio (>=5.13.0,<6.0.0)",
    "uvicorn (>=0.35.0,<0.36.0)",
    
    # Essential utilities 
    "python-dotenv (>=1.1.1,<2.0.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    
    # Modal client for GPU inference
    "modal (>=0.70.0,<1.0.0)",
    "aiohttp (>=3.11.0,<4.0.0)",
    
    # Minimal numpy for basic operations
    "numpy (>=2.3.2,<3.0.0)"
    
    # REMOVED: torch, transformers (only needed on Modal GPU)
    # These dependencies add ~2-4GB to image size
]

[project.optional-dependencies]
# Development dependencies (for local development only)
dev = [
    "black (>=25.1.0,<26.0.0)",
    "torch (>=2.7.1,<3.0.0)",
    "transformers (>=4.54.1,<5.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false